OSD-15291: Excluded SilentTest Alerts when kite --assigned-to team is run
openshift/pagerduty-short-circuiter pull request #103
Opened 2023-03-04 04:08 UTC by devppratik

### **Before the change :** 
When a user runs **kite alerts --assigned-to team**, they were shown all alerts assigned to their team.
![image](https://user-images.githubusercontent.com/56730201/222873716-952adc03-55bf-4377-bebd-bc4c097f15b9.png)

This included the alerts also assigned to Silent Test when the **kite alerts --assigned-to silentTest** command is run
![image](https://user-images.githubusercontent.com/56730201/222874652-5cd737da-3770-4547-b2cd-f55b63509383.png)

### **After the change :**
The kite alerts --assigned-to team removes every Silent Test alert from the list

![image](https://user-images.githubusercontent.com/56730201/222873684-b9ba8eb3-9c5b-403e-933d-6addbbd70aca.png)

2023-03-06 04:50 UTC, MitaliBhalla commented on pkg/pdcli/alerts/handlers.go
> +		// When incidents are fetched for a team, do not include the SilentTest incidents
```suggestion
		// When incidents are fetched for a team, do not include the incidents assigned to SilentTest
```

2023-03-06 07:32 UTC, supreeth7 commented
/hold

Changes requested concerning business logic

2023-03-07 09:27 UTC, supreeth7 requested changes
Overall looks good, nice work.
I've requested a few changes and we'll take it from then.

2023-03-07 09:27 UTC, supreeth7 commented on OWNERS
> -- devppratik
Lets not make any changes to the OWNERS file.

2023-03-07 09:27 UTC, supreeth7 commented on pkg/pdcli/alerts/handlers.go
> +	var areIncidentsFetchedForTeam bool = len(opts.TeamIDs) > 0
```suggestion
	 isTeam bool := len(opts.TeamIDs) > 0
```

2023-03-07 09:27 UTC, supreeth7 commented on pkg/pdcli/alerts/handlers.go
> +				continue
```suggestion
		if areIncidentsFetchedForTeam && incident.EscalationPolicy.ID == constants.SilentTestEscalationPolicyID || incident.EscalationPolicy.ID == constants.CADSilentTestEscalationPolicyID || incident.EscalationPolicy.ID == constants.CADSilentTestStageEscalationPolicyID {
				continue
```

2023-03-07 09:27 UTC, supreeth7 commented on pkg/pdcli/alerts/handlers.go
> +		if areIncidentsFetchedForTeam {
I would like you to add the `SilentTest` user to this conditional check, to skip incidents if assigned to that user.

2023-03-07 09:27 UTC, supreeth7 commented on pkg/pdcli/alerts/handlers.go
> +	listOfIncidents, err := c.ListIncidents(*opts)
```suggestion
	incidentsList, err := c.ListIncidents(*opts)
```

2023-03-10 03:28 UTC, supreeth7 commented
Thanks for appending the requested changes @devppratik!
While everything looks good, I can still see alerts not assigned to an SRE; the user is `Nobody SREP` whose ID is `P53J4TK`.
Can you avoid fetching alerts assigned to this user as well.
While you're at it, try using go `switch` statement, not a hard ask though.

2023-03-17 05:27 UTC, supreeth7 commented
/unhold

/lgtm
/approve

2023-03-17 05:33 UTC, merged