WIP OSD-15763 : Fix the program crashing error when many slides are removed at once
openshift/pagerduty-short-circuiter pull request #126
Opened 2023-04-17 04:29 UTC by Dee-6777

### What type of PR is this?

_bug_

### What this PR does / Why we need it?
Solves the bug which is occurred when any number of pages can be added or deleted and the app crashes.
Also solves app crashing when exit command & remove slide are executed simultaneously.
### Which Jira/Github issue(s) does this PR fix?

- _Resolves_ #[OSD-15766](https://issues.redhat.com/browse/OSD-15766)
- _Work in progress_ #[OSD-15763](https://issues.redhat.com/browse/OSD-15763)

### Special notes for your reviewer
For issue [OSD-15763](https://issues.redhat.com/browse/OSD-15763) some bugs are still not resolved :

- After continuous addition and deletion there comes a point where if we try to delete a page it throws an error `slice bound out of range [-1]` even if some pages are present.

### Pre-checks (if applicable)

- [X] Ran unit tests locally against the changes
- [ ] Included documentation changes with PR

2023-04-17 11:06 UTC, devppratik requested changes

2023-04-17 11:13 UTC, Dee-6777 commented on pkg/ui/tab.go
> +func indexOf(RegionIDs []int, ele int) int {
Thanks for the suggestion! Added it.

2023-04-17 11:13 UTC, Dee-6777 commented on pkg/ui/tab.go
> +	if len(tui.TerminalTabs) < 9 {
Yes sure!

2023-04-17 11:14 UTC, Dee-6777 commented on pkg/ui/tab.go
> +			if tab.primitive != nil {
Corrected. Thanks for highlighting this!

2023-04-19 10:34 UTC, supreeth7 approved these changes
/lgtm

2023-04-19 10:39 UTC, merged