OSD-16136 : In-built SOP Feature Added
openshift/pagerduty-short-circuiter pull request #128
Opened 2023-04-27 11:54 UTC by devppratik

### What type of PR is this?

_feature_

### What this PR does / Why we need it?
This PR adds the feature to view SOP related to alerts inside the kite interface itself
Pressing S on the alerts page, will open up the SOP on a new tab. 

![image](https://user-images.githubusercontent.com/56730201/234851902-dba0939b-dcc0-48a0-84db-e68149f7adb0.png)

### Which Jira/Github issue(s) does this PR fix?

_Resolves #OSD-16136_

### Special notes for your reviewer

### Pre-checks (if applicable)

- [ ] Ran unit tests locally against the changes
- [ ] Included documentation changes with PR

2023-04-28 13:39 UTC, supreeth7 requested changes

2023-04-28 13:39 UTC, supreeth7 commented on cmd/kite/login/cmd.go
> +		}
```suggestion
		if err = generateNewAccessToken(cfg); err != nil {
		return err
		}
```

2023-04-28 13:39 UTC, supreeth7 commented on cmd/kite/login/cmd.go
> +// generateNewKey prompts the user to create a new API key and saves it to the config file.
```suggestion
// generateNewAccessToken prompts the user to create a new API key and saves it to the config file.
```

2023-05-01 04:44 UTC, devppratik commented on cmd/kite/login/cmd.go
> +		}
Ack

2023-05-01 17:12 UTC, supreeth7 requested changes
Solid work on this!

We _really_ need to change the `login_test`, didn't realize it was all fairy dust without meaningful edge cases until I took a pass on it today. 

Please create a Jira to specifically **rewrite** all the `login` tests as part of M4.

2023-05-01 17:13 UTC, supreeth7 commented on cmd/kite/login/cmd.go
> +		"GitHub Personal Access Token generated from "+constants.AccessTokenURL+"\nUse this option to overwrite the existing Access Token.",
Nvm, this can be addressed in another PR.

2023-05-01 17:14 UTC, supreeth7 commented
Overriding CI to go over faulty tests for now.

/override ci/prow/coverage
/override ci/prow/test

2023-05-01 17:16 UTC, supreeth7 commented
Please comment out the entire `login_test.go` file and add a `// TODO` header so it doesn't block other PRs

2023-05-04 09:49 UTC, supreeth7 requested changes
@devppratik can you rebase?

2023-05-04 11:34 UTC, devppratik commented
@supreeth7 I have rebased the PR

2023-05-05 05:26 UTC, supreeth7 approved these changes
/lgtm

2023-05-05 05:30 UTC, merged