add changes to readme
openshift/pagerduty-short-circuiter pull request #133
Opened 2023-05-10 17:40 UTC by Dee-6777

### What type of PR is this?

_documentation_

### What this PR does / Why we need it?
It updates documentation for kite.
### Which Jira/Github issue(s) does this PR fix?

_Resolves_ [#OSD-15612](https://issues.redhat.com/browse/OSD-15612)

### Pre-checks (if applicable)

- [ ] Ran unit tests locally against the changes
- [x] Included documentation changes with PR

2023-05-11 03:56 UTC, supreeth7 requested changes

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +- Users can see whom the alerts is being assigned to
```suggestion
- Users can see whom the alerts are being assigned to
```

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +- Users can see whom the alerts is being assigned to
```suggestion
- Users can see whom the alerts are being assigned to
```

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +- Users can create a new window named `<cluster name>` and switch to that window
This isn't needed
```suggestion
```

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +After this, it will ask you a **Github Access Token**. Users need to create a **GitHub Access Token** (Classic) with read-only access.
```suggestion
Upon login, kite will ask the user to enter a [Github Access Token](https://github.com/settings/tokens). Users need to create a classic access token with read-only access.
```

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +To view the PagerDuty alerts that has been assigned to your team, use the command:
```suggestion
To view the PagerDuty alerts that have been assigned to your team, use the command:
```

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +To view the PagerDuty alerts that has been assigned to silentTest, use the command:
```suggestion
To view the PagerDuty alerts that have been assigned to Silent Test, use the command:
```

2023-05-11 03:56 UTC, supreeth7 commented on README.md
> +This will list all the terminal qemulators supported by the system and will prompt the user to select an emulator for kite.
```suggestion
This will list all the terminal emulators supported by the system and will prompt the user to select an emulator for kite.
```

2023-05-11 03:56 UTC, supreeth7 commented
I see no mention of `Tmux` anywhere in the docs. Please include it and its usage in kite.

2023-05-11 04:23 UTC, Dee-6777 commented
> I see no mention of `Tmux` anywhere in the docs. Please include it and its usage in kite.

I have added about that under Terminal Multiplexer.

2023-05-18 05:10 UTC, supreeth7 commented on README.md
> +## List
What does this header imply here?

2023-05-18 05:11 UTC, supreeth7 requested changes

2023-05-18 05:11 UTC, supreeth7 commented on README.md
> +- Users can see whom the alerts are being assigned to
```suggestion
- Users can see whom the alerts have been assigned to
```

2023-06-30 22:28 UTC, closed without merging